Feat: parse isLive in CompactVideo
LuanRT/YouTube.js pull request #294
Opened 2023-01-25 02:13 UTC by ChunkyProgrammer

# Feat: parse isLive in CompactVideo

## Description

This looks for a badge to determine if a CompactVideo is live

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-01-25 02:14 UTC, ChunkyProgrammer commented
Using this video https://youtu.be/jfKfPfyJRdk I find that you can consistently find live and non live videos in the watch_next_feed

2023-01-25 07:18 UTC, absidue commented on src/parser/classes/CompactVideo.ts
> +    this.is_live = data.badges?.some((badge: any) => badge.metadataBadgeRenderer.style == 'BADGE_STYLE_TYPE_LIVE_NOW') || false;
Please use 3 equals signs here, as you want to compare the exact values.
```suggestion
    this.is_live = data.badges?.some((badge: any) => badge.metadataBadgeRenderer.style === 'BADGE_STYLE_TYPE_LIVE_NOW') || false;
```

2023-01-25 23:07 UTC, LuanRT requested changes
Looks good. The only thing I think should be changed here is how the badge renderers are being accessed, they should go through the parser first and only then they should be used.

The `Video` node is a good example:
https://github.com/LuanRT/YouTube.js/blob/0fc29f0bbf965215146a6ae192494c74e6cefcbb/src/parser/classes/Video.ts#L68
https://github.com/LuanRT/YouTube.js/blob/0fc29f0bbf965215146a6ae192494c74e6cefcbb/src/parser/classes/Video.ts#L97-L102

2023-01-27 17:40 UTC, LuanRT approved these changes

2023-01-27 17:44 UTC, merged