feat: add possibility to add playlists to user library
LuanRT/YouTube.js pull request #844
Opened 2024-12-14 22:39 UTC by Duell10111

Adds the possibility to add a external playlist to a user library.

Worked as sharm with v11, I adapted it to v12 structure. :)

2024-12-15 04:08 UTC, LuanRT requested changes
I think `addToLibrary` and `removeFromLibrary` would suit these methods better.

2024-12-15 14:25 UTC, Duell10111 commented
> I think `addToLibrary` and `removeFromLibrary` would suit these methods better. Looks good otherwise.

Alright, renamed the methods. :)

2024-12-15 14:57 UTC, Duell10111 reviewed
Method names changed.

2024-12-31 09:23 UTC, LuanRT approved these changes

2024-12-31 09:23 UTC, merged